### PR TITLE
adding optional authentication handler

### PR DESCRIPTION
**Pull request by NoamB**
A historic moment - My first PR in Github ever... (though I've accepted many myself...)

See issue #5 for background.

This patch allows the developer to add an optional auth-handler (ring-handler) in the configurator options.
This handler is ran with the original request, and can reject the user by not returning 200 OK.
In addition, the session map, if available, is attached to the request passed down the channel, and enables you to identify the user, which can be very useful.

The test file keeps compiling as before unchanged.

### CODE REVIEW

**Comment by lynaghk** [comment]
Can you clarify on why you chose a ring handler vs. a plain function of the request map that returns true/false?

Also, a few comments:
- please use `when` instead of `if` for expressions that don't have an else clause
- it's hard to see what is going on since there are a lot of whitespace changes
- please squash your changes into a single commit
- can you implement a few test cases? this may help clarify the API

@zachallaun, do you have any thoughts on this functionality?

**Comment by NoamB** [comment]
Hi,
Cleaned up the patch as requested.

Regarding why ring handler - In the normal HTTP handler (non-websocket) I'm using ring-middleware like `wrap-session` and others. Ideally, I would like to run the websocket request through the same stack.

Using the same stack I can get the user logged-in via a normal HTTP request, and then get the ring-session loaded automatically when using `wrap-session` again on the websocket request. The only difference is I need to extract the session out of the response in a 'hacky' way, to be able to pass it downstream. So true/false here is enough for rejecting, but not enough for knowing which user this is incase you don't reject them.

I'm not confident this is the nicest way to achieve this... and I'm open for suggestions.

**Comment by lynaghk** [comment]
Thanks for the prompt cleanup---the commit still needs tests, though.

I agree that it makes sense to pass the request map to the auth handler---I'm more concerned about the response.
There are only two possible actions (allow, don't allow), so a boolean value makes more sense than demanding a response map.

Let me stew on it over the holidays...

**Comment by NoamB** [comment]
There are 2 possible actions in the short term (allow, don't allow).

Now let's suppose we allow - how do we know which user it is when handling a WS message? Authenticate again using WS messages? Redundant - We already authenticated and have a session-cookie.

My way extracts the session map from the auth-handler (assuming you are using something like `wrap-session`) and enables passing it to any function that needs it. That's why a map response is needed (for the session map).

And with that I'll say, Happy Holidays! :)

**Comment by ToBeReplaced** [comment]
Bumping this one in case it's just been on the backburner.  The explicit `:session` closes off other potential middlewares.  I'd rather see a `:auth-info` key that is the result of applying an optional auth-handler that defaults to `(constantly true)`.  Then, instead of checking for status, we could just check for truthiness.  

If you want to use existing ring middleware, you'd need to wrap it once more with:

``` clojure
(defn success-only 
  [handler] 
  (fn [request] 
    (let [response (handler request)] 
      (when (< 199 (:status response) 300) response))))
```

**Comment by lynaghk** [comment]
The patch is still on the backburner because @NoamB hasn't updated it with any tests.

However, I'm still not convinced that this auth-handler is the best way to go.
I'd like to avoid bringing any authentication/authorization concerns into what is right now a very simple library.

@NoamB, what do you think about this alternative approach: use standard Ring stack with auth library of your choice (e.g., Friend) to serve the user a unique token over HTTPS that they then use to request a websocket connection?
They could actually request `/ws/token-id` as a URI, or do something like send the token to the server to associate that websocket connection with the user.

**Comment by NoamB** [comment]
@lynaghk, I don't think you can escape adding authentication concerns to the websocket handler as there are real use cases where you can't just allow anyone to connect, and you may want to reject them before the connection was upgraded to websocket, saving your resources.

What I'm doing today is login in a usual form over HTTPS, returning a cookie and later authenticating with it using a ring handler _pre websocket creation_ (with [this](https://github.com/sunng87/ring-jetty9-adapter) adapter).

That said, replacing the ring handler with a function that takes a request map (or token) and returns either a session (a map) or nil, is probably a nicer interface than checking for status 200 (and it can still use a ring handler internally). I will try that on my code.

I'm currently very occupied with other burning projects so I won't be updating this patch. I'll close it to clear it from your queue and if anyone wants to take it from here they are welcome.

**Comment by lynaghk** [comment]
@NoamB Avoiding additional scope is my most effective programming skill = )

My hope is that there's some corner of the websocket spec that describes how to handle this situation.
I agree with you that it's gross to try and have two separate auth mechanisms (one for HTTP, one for websockets), but until I'm convinced of a good way to unify them I'd rather punt on the issue.

Thank you for the discussion!

**Comment by ToBeReplaced** [comment]
Okay, fair enough.  Neither this library nor ring-jetty9-adapter meets my needs, so I had to create something separate.  I pushed back on some of the design decisions in both libraries, and would be interested in your feedback.

https://github.com/ToBeReplaced/jetty9-websockets-async

**Comment by lynaghk** [comment]
@ptaoussanis just released https://github.com/ptaoussanis/sente today, which looks much more featured than my lil' wrapper.
He may have some good suggestions on the auth question.

**Pull request closed without merging**
