### PR TITLE
Build & pass request map, not just URI

### PR DESCRIPTION
**Pull request by loganlinn**
I needed cookie/session data when handling my websockets, so I'm building a request map using ring-servlet and adding to map sent over connection-chan rather than just URI. Allows access to basic set of request data, including headers, query params, [etc](https://github.com/ring-clojure/ring/blob/0cf09cc9a57e8a4422cdaa5783e62b7890a745d4/ring-servlet/src/ring/util/servlet.clj#L34-49). Not sure if you're interested in this, @lynaghk, since it changes the interface slightly, but others might find this helpful. I'll update the tests if you are interested

### CODE REVIEW

**Comment by lynaghk** [comment]
Whoa, I had no idea websocket connections even passed this kind of thing along (cookies, &c.).
I can see cookies being useful, but do you think many applications will be trying to open up websocket connections and pass along query params at the same time?
Can you say anything more about your use case?

@zachallaun Do you have any thoughts on this? I'm open to changing the API a bit, considering that there hasn't yet been a non-SNAPSHOT release.

**Comment by zachallaun** [comment]
I could imagine a client configuring a new connection using query params.
I'm in favour of the change.

**Comment by loganlinn** [comment]
> Can you say anything more about your use case?

Currently using this for building a game over websockets. Having access to cookie allows me to securely identify each game client rather than having my client identify itself upon connecting. I do not currently have use for query params or other data sent w/ request, such as user agent, but it seems like useful information that doesn't hurt to be passed along.

I will try to update the tests/docs later to get into a more mergable state

**Comment by lynaghk** [comment]
@loganlinn I'm sold, it sounds like a good change to me and doesn't add any additional dependencies or real overhead. Please update the tests/docs and amend the commit.
Let me know if there are any parts you'd like me to help with.

Thanks for the pull request!

**Comment by loganlinn** [comment]
Ok, tests updated -- let me know what you think

**Comment by lynaghk** [comment]
Okay, merged into master and released as version 0.1.0. Thanks for submitting this @loganlinn!

**Pull request merged**
